export const NODE_PATH = process.execPath;
export const ENV_COMMITIZEN = 'RISEUP_COMMITIZEN';
export const ENV_SEMANTIC = 'RISEUP_SEMANTIC';
export const ENV_RELEASE = 'RISEUP_RELEASE';
export const ENV_MONOREPO_VALIDATE = 'RISEUP_MONOREPO_VALIDATE';
